mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.sadowbass.outerpark
spring:
  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/outerpark
    username: root
    password:
  redis:
    host: 127.0.0.1
    port: 6379
    password:
  session:
    store-type: redis
    redis:
      namespace: outerpark:session

server:
  servlet:
    session:
      cookie:
        path: /
        name: OUTERPARK-SESSION-ID
      timeout: 60m
